/* DEBUT DU SCRIPT*/

/* REM ETAPE 1 : SUPPRESSION DES TABLES*/

/* REM ETAPE 2 : CREATION DES TABLES*/

CREATE TABLE Avis
(
idAvis INTEGER AUTO_INCREMENT PRIMARY KEY,
UPPER(Nom) VARCHAR(50),
Prenom VARCHAR(50),
Avis VARCHAR(100)
);

/* REM ETAPE 3 : CREATION DES CONTRANTES*/

ALTER TABLE Avis
ADD CONSTRAINT U_Nom_Prenom UNIQUE(Nom, Prenom);


/* REM SCRIPT COMPLETEMENT TERMINE*/