/* DEBUT DU SCRIPT*/

/* REM ETAPE 1 : SUPPRESSION DES TABLES*/

/* REM ETAPE 2 : CREATION DES TABLES*/

CREATE TABLE compte
(
idCompte INTEGER AUTO_INCREMENT PRIMARY KEY,
Nom VARCHAR(50),
Prenom VARCHAR(50),
Mail VARCHAR(50),
Mdp VARCHAR(50)
);

CREATE TABLE parc
(
idParc INTEGER PRIMARY KEY,
Nom VARCHAR(50)
);

CREATE TABLE commentaire
(
idCompte INTEGER,
idParc INTEGER,
idCom INTEGER,
Nom VARCHAR(50) NOT NULL,
Prenom VARCHAR(50)NOT NULL,
Commentaire VARCHAR(255)
);

/* REM ETAPE 3 : CREATION DES CONTRANTES*/

ALTER TABLE compte
ADD CONSTRAINT U_Nom_Prenom_Mail UNIQUE(Nom, Prenom, Mail);

ALTER TABLE compte
ADD CONSTRAINT U_Mail UNIQUE(Mail);

ALTER TABLE commentaire
ADD CONSTRAINT PK_idCompte_idParc PRIMARY KEY(idCompte, idParc);

ALTER TABLE commentaire
ADD CONSTRAINT FK_idCompte FOREIGN KEY(idCompte) REFERENCES Compte(IdCompte);

ALTER TABLE commentaire
ADD CONSTRAINT FK_idCompte_idParc FOREIGN KEY(idParc) REFERENCES Parc(idParc);

ALTER TABLE commentaire
ADD CONSTRAINT U_idCom UNIQUE(idCom);

ALTER TABLE commentaire CHANGE idCom idCom INT(11) NOT NULL AUTO_INCREMENT;

/* REM ETAPE 4 : INSERTION DES DONNEES*/

INSERT INTO compte (Nom, Prenom, Mail, Mdp) 
VALUES('Marheraoui', 'Amin', 'amin.marheraoui@hotmail.com', 'amintest');

/* REM SCRIPT COMPLETEMENT TERMINE*/